---
RecipeFormatVersion: '2020-01-25'
ComponentName: com.example.ListS3Buckets
ComponentVersion: '1.0.0'
ComponentDescription: A component that uses the token exchange service to list S3 buckets.
ComponentPublisher: Amazon
ComponentDependencies:
  aws.greengrass.TokenExchangeService:
    VersionRequirement: '^2.0.0'
    DependencyType: HARD
Manifests:
  - Platform:
      os: linux
    Artifacts:
      - URI: "s3://YOUR BUCKET NAME - YOUR AWS REGION - YOUR AWS ID/com.example.ListS3Buckets/1.0.0/ListS3Buckets-python.zip"
        Unarchive: ZIP
    Lifecycle:
      Run: |-
        python3 -u {artifacts:decompressedPath}/ListS3Buckets-python/list_s3_buckets.py
